var car = "subaru";
console.log(car == "subaru");
var fruit = "orange";
console.log(car == "banana");
var bird = "hen";
console.log(bird == "hen");
var cell = "nokia";
console.log(cell == "vivo");
var bike = "honda";
console.log(bike == "honda");
var laptop = "dell";
console.log(laptop == "lenovo");
var number = 123;
console.log(number == 123);
var country = "spain";
console.log(country == "korea");
var lang = "urdu";
console.log(lang == "urdu");
var student = "ali";
console.log(student == "usman");
var school = "governor house";
console.log(school == "governor house");
